# Generated by Django 4.2.4 on 2023-08-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("10", "10대"),
                            ("20", "20대"),
                            ("30", "30대"),
                            ("40", "40대"),
                            ("50", "50대"),
                            ("60", "60대 이상"),
                        ],
                        default=0,
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, unique=True, verbose_name="메뉴명"),
                ),
                ("en_title", models.CharField(default="", max_length=250)),
                ("price", models.IntegerField(default="0", verbose_name="가격")),
                ("image", models.ImageField(upload_to="menu/images/")),
                ("desc", models.CharField(default="", max_length=250)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bugger", " bugger"),
                            ("set menu", "set menu"),
                            ("drink", "drink"),
                            ("side", "side"),
                        ],
                        default=0,
                        max_length=20,
                    ),
                ),
                ("is_best_menu", models.BooleanField(default=False)),
                ("created", models.DateField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("calorie", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.FileField(blank=True, upload_to="model/")),
                ("version", models.CharField(max_length=10)),
                ("comment", models.CharField(default=" ", max_length=300)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("count", models.IntegerField(default=0, verbose_name="수량")),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bugger.customer",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bugger.menu"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
