# Generated by Django 4.2.4 on 2023-08-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="type",
            field=models.CharField(
                choices=[
                    ("bugger", " bugger"),
                    ("set_menu", "set_menu"),
                    ("drink", "drink"),
                    ("side", "side"),
                ],
                default=0,
                max_length=20,
            ),
        ),
    ]
