# Generated by Django 4.2.4 on 2023-10-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugger", "0009_alter_menu_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="type",
            field=models.CharField(
                choices=[
                    ("bugger", " bugger"),
                    ("New", "New"),
                    ("Premium", "Premium"),
                    ("drink", "drink"),
                    ("side", "side"),
                    ("Whopper", "Whopper"),
                    ("set_change", "set_change"),
                    ("old_B", "old_B"),
                    ("old_P", "old_P"),
                    ("old_W", "old_W"),
                    ("old_side", "lod_side"),
                ],
                default=0,
                max_length=20,
            ),
        ),
    ]
