# Generated by Django 4.2.4 on 2023-10-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugger", "0011_alter_menu_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="explanation",
            field=models.CharField(default="", max_length=250),
        ),
    ]
